### ISSUE TITLE
Getting Started Videos in README

### ISSUE THREAD

**Issue by SirLouen** [Volte6/GoMud#142]
In the README.md the link its wrong, its linking to an image

```
Quick Start
A youtube playlist to getting started has been set up here:

[Getting Started Videos](https://i.ytimg.com/vi/OOZqX01aHt8/hqdefault.jpg)
```

**Comment by Volte6** [comment]
Thank you, i will update that today.

Were you able to find the playlist?

I should update/revise a lot of those, since there has been a fair amount of change and improvements over the last year.

If activity and interest picks up, i may eventually do some livestreams that I think would be a lot more interesting and informative. Seeing the process for adding content or features with the ability for questions/feedback is a lot more insightful than cold demos and documentation.

**Comment by Volte6** [comment]
This is fixed. Closing issue.
