### ISSUE TITLE
Prompt bar is redisplaying over and over in a noisy fashion.

### ISSUE THREAD

**Issue by ArmoredArtist** [Volte6/GoMud#81]
![image](https://github.com/user-attachments/assets/27f46f24-8537-4c97-a963-8fc2202bb62c)

The prompt bar seems to be on some kind of ticker that keeps firing off causing screen spam:

[⚙ 9:50AM HP:44/44 MP:32/32]:

**Comment by Volte6** [comment]
Yeah, basically the server sends a command intended to redraw that line, but mudlet refuses to support the escape sequence that moves the cursor to the beginning, and instead just makes a new line.

It's frustrating because it's a normal command they don't want to support. Mudlet detection or at least a mudlet setting for clients will probably be required in the future to deal with special considerations that are mudlet specific.

I discuss this a bit more in depth here: https://www.reddit.com/r/MUD/comments/1d3f0fo/comment/l67grd5/

**Comment by Volte6** [comment]
As an aside - That's funny the icon I use for the sun shows as a gear for you (because its' a gear emoji). Maybe I should change it to the actual sun: ☀️ ... I just didn't like how it forced color/styling

**Comment by windu-ant** [comment]
I made a really dirty fix for this 6 months ago. You could go a step further and detect the client, it's done in Smaug but I'd have to go look up how. 

https://reddit.com/r/MUD/comments/1b1k0pa/_/ksltb1g/?context=1

**Comment by Volte6** [comment]
I can go ahead and dial that back, but my main issue was that there are several cases where I redraw the prompt in order to maintain what's being typed in the terminal or suggestions when hitting tab in telnet etc., so I need to put a lot of special consideration into it.

I'll look into how to detect if it's mudlet since that would be the quickest fix to disable prompt redrawing. I can also probably cache the last rendered prompt and only update if it has changed.

**Comment by Volte6** [comment]
Okay I put in a caching step to prevent redrawing if the prompt hasn't changed... this should cover more than HP/MP changes, basically if anything that would display in the prompt changes (or doesn't). ( see `help prompt` )

https://github.com/Volte6/GoMud/pull/83

**Comment by Volte6** [comment]
Closing as completed.
